num_questions_random: 20
subjects: 
  - "MySQL Test"
  - "Ruby On Rails Test"
  - "Git Test"
levels:
  normal: 0
  advanced: 1
user_levels:
  - "admin"
  - "normal"
types:
  - single_choice
  - multiple_choices
  - text
